/* Automatically generated by tree-sitter v0.25.3 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 23
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 22
#define ALIAS_COUNT 0
#define TOKEN_COUNT 10
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_u00ab = 1,
  anon_sym_u00bb = 2,
  sym_item_id = 3,
  aux_sym_item_content_token1 = 4,
  anon_sym_LBRACE_DASH = 5,
  anon_sym_DASH_RBRACE = 6,
  aux_sym_item_note_inner_token1 = 7,
  sym_footer_prefix = 8,
  aux_sym_footer_content_token1 = 9,
  sym_source_file = 10,
  sym_item = 11,
  sym_item_marker = 12,
  sym_item_content = 13,
  sym_item_note = 14,
  sym_item_note_inner = 15,
  sym_footer = 16,
  sym_footer_content = 17,
  aux_sym_source_file_repeat1 = 18,
  aux_sym_item_content_repeat1 = 19,
  aux_sym_item_note_inner_repeat1 = 20,
  aux_sym_footer_content_repeat1 = 21,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_u00ab] = "\u00ab",
  [anon_sym_u00bb] = "\u00bb",
  [sym_item_id] = "item_id",
  [aux_sym_item_content_token1] = "item_content_token1",
  [anon_sym_LBRACE_DASH] = "{-",
  [anon_sym_DASH_RBRACE] = "-}",
  [aux_sym_item_note_inner_token1] = "item_note_inner_token1",
  [sym_footer_prefix] = "footer_prefix",
  [aux_sym_footer_content_token1] = "footer_content_token1",
  [sym_source_file] = "source_file",
  [sym_item] = "item",
  [sym_item_marker] = "item_marker",
  [sym_item_content] = "item_content",
  [sym_item_note] = "item_note",
  [sym_item_note_inner] = "item_note_inner",
  [sym_footer] = "footer",
  [sym_footer_content] = "footer_content",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_item_content_repeat1] = "item_content_repeat1",
  [aux_sym_item_note_inner_repeat1] = "item_note_inner_repeat1",
  [aux_sym_footer_content_repeat1] = "footer_content_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_u00ab] = anon_sym_u00ab,
  [anon_sym_u00bb] = anon_sym_u00bb,
  [sym_item_id] = sym_item_id,
  [aux_sym_item_content_token1] = aux_sym_item_content_token1,
  [anon_sym_LBRACE_DASH] = anon_sym_LBRACE_DASH,
  [anon_sym_DASH_RBRACE] = anon_sym_DASH_RBRACE,
  [aux_sym_item_note_inner_token1] = aux_sym_item_note_inner_token1,
  [sym_footer_prefix] = sym_footer_prefix,
  [aux_sym_footer_content_token1] = aux_sym_footer_content_token1,
  [sym_source_file] = sym_source_file,
  [sym_item] = sym_item,
  [sym_item_marker] = sym_item_marker,
  [sym_item_content] = sym_item_content,
  [sym_item_note] = sym_item_note,
  [sym_item_note_inner] = sym_item_note_inner,
  [sym_footer] = sym_footer,
  [sym_footer_content] = sym_footer_content,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_item_content_repeat1] = aux_sym_item_content_repeat1,
  [aux_sym_item_note_inner_repeat1] = aux_sym_item_note_inner_repeat1,
  [aux_sym_footer_content_repeat1] = aux_sym_footer_content_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_u00ab] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u00bb] = {
    .visible = true,
    .named = false,
  },
  [sym_item_id] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_item_content_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACE_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_item_note_inner_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_footer_prefix] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_footer_content_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_item] = {
    .visible = true,
    .named = true,
  },
  [sym_item_marker] = {
    .visible = true,
    .named = true,
  },
  [sym_item_content] = {
    .visible = true,
    .named = true,
  },
  [sym_item_note] = {
    .visible = true,
    .named = true,
  },
  [sym_item_note_inner] = {
    .visible = true,
    .named = true,
  },
  [sym_footer] = {
    .visible = true,
    .named = true,
  },
  [sym_footer_content] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_item_content_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_item_note_inner_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_footer_content_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(14);
      if (lookahead == '-') ADVANCE(6);
      if (lookahead == '{') ADVANCE(1);
      if (lookahead == 0xab) ADVANCE(15);
      if (lookahead == 0xbb) ADVANCE(16);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '-') ADVANCE(23);
      END_STATE();
    case 2:
      if (lookahead == '-') ADVANCE(27);
      END_STATE();
    case 3:
      if (lookahead == '-') ADVANCE(27);
      if (lookahead != 0) ADVANCE(19);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(11);
      if (lookahead != 0) ADVANCE(19);
      END_STATE();
    case 5:
      if (lookahead == '-') ADVANCE(9);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(26);
      if (lookahead != 0) ADVANCE(25);
      END_STATE();
    case 6:
      if (lookahead == '-') ADVANCE(2);
      if (lookahead == '}') ADVANCE(24);
      END_STATE();
    case 7:
      if (lookahead == '-') ADVANCE(3);
      if (lookahead != 0) ADVANCE(19);
      END_STATE();
    case 8:
      if (lookahead == '-') ADVANCE(4);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(22);
      if (lookahead != 0 &&
          lookahead != 0xab) ADVANCE(19);
      END_STATE();
    case 9:
      if (lookahead == '}') ADVANCE(24);
      if (lookahead != 0) ADVANCE(25);
      END_STATE();
    case 10:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(17);
      if (lookahead != 0 &&
          lookahead != 0xbb) ADVANCE(18);
      END_STATE();
    case 11:
      if (lookahead != 0 &&
          lookahead != '-') ADVANCE(19);
      END_STATE();
    case 12:
      if (eof) ADVANCE(14);
      if (lookahead == '\n') SKIP(12);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(29);
      if (lookahead != 0) ADVANCE(28);
      END_STATE();
    case 13:
      if (eof) ADVANCE(14);
      if (lookahead == '-') ADVANCE(7);
      if (lookahead == '{') ADVANCE(20);
      if (lookahead == 0xab) ADVANCE(15);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0) ADVANCE(19);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_u00ab);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_u00bb);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_item_id);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(17);
      if (lookahead != 0 &&
          lookahead != 0xbb) ADVANCE(18);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_item_id);
      if (lookahead != 0 &&
          lookahead != 0xbb) ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_item_content_token1);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_item_content_token1);
      if (lookahead == '-') ADVANCE(23);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_item_content_token1);
      if (lookahead == '-') ADVANCE(7);
      if (lookahead == '{') ADVANCE(20);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != 0xab) ADVANCE(19);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_item_content_token1);
      if (lookahead == '-') ADVANCE(4);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(22);
      if (lookahead != 0 &&
          lookahead != 0xab) ADVANCE(19);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_LBRACE_DASH);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_DASH_RBRACE);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_item_note_inner_token1);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_item_note_inner_token1);
      if (lookahead == '-') ADVANCE(9);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(26);
      if (lookahead != 0) ADVANCE(25);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_footer_prefix);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_footer_content_token1);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_footer_content_token1);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(29);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(28);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 13},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 13},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 12},
  [8] = {.lex_state = 8},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 12},
  [11] = {.lex_state = 5},
  [12] = {.lex_state = 5},
  [13] = {.lex_state = 12},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 5},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 10},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 8},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_u00ab] = ACTIONS(1),
    [anon_sym_u00bb] = ACTIONS(1),
    [anon_sym_LBRACE_DASH] = ACTIONS(1),
    [anon_sym_DASH_RBRACE] = ACTIONS(1),
    [sym_footer_prefix] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(18),
    [sym_item] = STATE(2),
    [sym_item_marker] = STATE(8),
    [aux_sym_source_file_repeat1] = STATE(2),
    [anon_sym_u00ab] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(3), 1,
      anon_sym_u00ab,
    ACTIONS(5), 1,
      ts_builtin_sym_end,
    ACTIONS(7), 1,
      sym_footer_prefix,
    STATE(8), 1,
      sym_item_marker,
    STATE(19), 1,
      sym_footer,
    STATE(4), 2,
      sym_item,
      aux_sym_source_file_repeat1,
  [20] = 4,
    ACTIONS(9), 1,
      ts_builtin_sym_end,
    ACTIONS(13), 1,
      aux_sym_item_content_token1,
    STATE(5), 1,
      aux_sym_item_content_repeat1,
    ACTIONS(11), 3,
      anon_sym_u00ab,
      anon_sym_LBRACE_DASH,
      sym_footer_prefix,
  [35] = 4,
    ACTIONS(17), 1,
      anon_sym_u00ab,
    STATE(8), 1,
      sym_item_marker,
    ACTIONS(15), 2,
      ts_builtin_sym_end,
      sym_footer_prefix,
    STATE(4), 2,
      sym_item,
      aux_sym_source_file_repeat1,
  [50] = 4,
    ACTIONS(20), 1,
      ts_builtin_sym_end,
    ACTIONS(24), 1,
      aux_sym_item_content_token1,
    STATE(5), 1,
      aux_sym_item_content_repeat1,
    ACTIONS(22), 3,
      anon_sym_u00ab,
      anon_sym_LBRACE_DASH,
      sym_footer_prefix,
  [65] = 3,
    ACTIONS(29), 1,
      anon_sym_LBRACE_DASH,
    STATE(9), 1,
      sym_item_note,
    ACTIONS(27), 3,
      ts_builtin_sym_end,
      anon_sym_u00ab,
      sym_footer_prefix,
  [77] = 4,
    ACTIONS(31), 1,
      ts_builtin_sym_end,
    ACTIONS(33), 1,
      aux_sym_footer_content_token1,
    STATE(10), 1,
      aux_sym_footer_content_repeat1,
    STATE(21), 1,
      sym_footer_content,
  [90] = 3,
    ACTIONS(35), 1,
      aux_sym_item_content_token1,
    STATE(3), 1,
      aux_sym_item_content_repeat1,
    STATE(6), 1,
      sym_item_content,
  [100] = 1,
    ACTIONS(37), 3,
      ts_builtin_sym_end,
      anon_sym_u00ab,
      sym_footer_prefix,
  [106] = 3,
    ACTIONS(39), 1,
      ts_builtin_sym_end,
    ACTIONS(41), 1,
      aux_sym_footer_content_token1,
    STATE(13), 1,
      aux_sym_footer_content_repeat1,
  [116] = 3,
    ACTIONS(43), 1,
      aux_sym_item_note_inner_token1,
    STATE(12), 1,
      aux_sym_item_note_inner_repeat1,
    STATE(22), 1,
      sym_item_note_inner,
  [126] = 3,
    ACTIONS(45), 1,
      anon_sym_DASH_RBRACE,
    ACTIONS(47), 1,
      aux_sym_item_note_inner_token1,
    STATE(15), 1,
      aux_sym_item_note_inner_repeat1,
  [136] = 3,
    ACTIONS(49), 1,
      ts_builtin_sym_end,
    ACTIONS(51), 1,
      aux_sym_footer_content_token1,
    STATE(13), 1,
      aux_sym_footer_content_repeat1,
  [146] = 1,
    ACTIONS(54), 3,
      ts_builtin_sym_end,
      anon_sym_u00ab,
      sym_footer_prefix,
  [152] = 3,
    ACTIONS(56), 1,
      anon_sym_DASH_RBRACE,
    ACTIONS(58), 1,
      aux_sym_item_note_inner_token1,
    STATE(15), 1,
      aux_sym_item_note_inner_repeat1,
  [162] = 1,
    ACTIONS(61), 1,
      anon_sym_u00bb,
  [166] = 1,
    ACTIONS(63), 1,
      sym_item_id,
  [170] = 1,
    ACTIONS(65), 1,
      ts_builtin_sym_end,
  [174] = 1,
    ACTIONS(67), 1,
      ts_builtin_sym_end,
  [178] = 1,
    ACTIONS(69), 1,
      aux_sym_item_content_token1,
  [182] = 1,
    ACTIONS(71), 1,
      ts_builtin_sym_end,
  [186] = 1,
    ACTIONS(73), 1,
      anon_sym_DASH_RBRACE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 20,
  [SMALL_STATE(4)] = 35,
  [SMALL_STATE(5)] = 50,
  [SMALL_STATE(6)] = 65,
  [SMALL_STATE(7)] = 77,
  [SMALL_STATE(8)] = 90,
  [SMALL_STATE(9)] = 100,
  [SMALL_STATE(10)] = 106,
  [SMALL_STATE(11)] = 116,
  [SMALL_STATE(12)] = 126,
  [SMALL_STATE(13)] = 136,
  [SMALL_STATE(14)] = 146,
  [SMALL_STATE(15)] = 152,
  [SMALL_STATE(16)] = 162,
  [SMALL_STATE(17)] = 166,
  [SMALL_STATE(18)] = 170,
  [SMALL_STATE(19)] = 174,
  [SMALL_STATE(20)] = 178,
  [SMALL_STATE(21)] = 182,
  [SMALL_STATE(22)] = 186,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_item_content, 1, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_item_content, 1, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [17] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [20] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_item_content_repeat1, 2, 0, 0),
  [22] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_item_content_repeat1, 2, 0, 0),
  [24] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_item_content_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_item, 2, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_footer, 1, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_item, 3, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_footer_content, 1, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [45] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_item_note_inner, 1, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_footer_content_repeat1, 2, 0, 0),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_footer_content_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_item_note, 3, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_item_note_inner_repeat1, 2, 0, 0),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_item_note_inner_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [65] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_item_marker, 3, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_footer, 2, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_ats(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "ats",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
