/* Automatically generated by tree-sitter v0.25.3 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 17
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 16
#define ALIAS_COUNT 0
#define TOKEN_COUNT 7
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_u00ab = 1,
  anon_sym_u00bb = 2,
  sym_entry_id = 3,
  aux_sym__inner_token1 = 4,
  sym_note_prefix = 5,
  aux_sym_note_content_token1 = 6,
  sym_source_file = 7,
  sym_entry = 8,
  sym_entry_marker = 9,
  sym_entry_content = 10,
  aux_sym__inner = 11,
  sym_note = 12,
  sym_note_content = 13,
  aux_sym_source_file_repeat1 = 14,
  aux_sym_note_content_repeat1 = 15,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_u00ab] = "\u00ab",
  [anon_sym_u00bb] = "\u00bb",
  [sym_entry_id] = "entry_id",
  [aux_sym__inner_token1] = "_inner_token1",
  [sym_note_prefix] = "note_prefix",
  [aux_sym_note_content_token1] = "note_content_token1",
  [sym_source_file] = "source_file",
  [sym_entry] = "entry",
  [sym_entry_marker] = "entry_marker",
  [sym_entry_content] = "entry_content",
  [aux_sym__inner] = "_inner",
  [sym_note] = "note",
  [sym_note_content] = "note_content",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_note_content_repeat1] = "note_content_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_u00ab] = anon_sym_u00ab,
  [anon_sym_u00bb] = anon_sym_u00bb,
  [sym_entry_id] = sym_entry_id,
  [aux_sym__inner_token1] = aux_sym__inner_token1,
  [sym_note_prefix] = sym_note_prefix,
  [aux_sym_note_content_token1] = aux_sym_note_content_token1,
  [sym_source_file] = sym_source_file,
  [sym_entry] = sym_entry,
  [sym_entry_marker] = sym_entry_marker,
  [sym_entry_content] = sym_entry_content,
  [aux_sym__inner] = aux_sym__inner,
  [sym_note] = sym_note,
  [sym_note_content] = sym_note_content,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_note_content_repeat1] = aux_sym_note_content_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_u00ab] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u00bb] = {
    .visible = true,
    .named = false,
  },
  [sym_entry_id] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__inner_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_note_prefix] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_note_content_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_entry_marker] = {
    .visible = true,
    .named = true,
  },
  [sym_entry_content] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__inner] = {
    .visible = false,
    .named = false,
  },
  [sym_note] = {
    .visible = true,
    .named = true,
  },
  [sym_note_content] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_note_content_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(8);
      if (lookahead == '-') ADVANCE(3);
      if (lookahead == 0xab) ADVANCE(9);
      if (lookahead == 0xbb) ADVANCE(10);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '-') ADVANCE(15);
      END_STATE();
    case 2:
      if (lookahead == '-') ADVANCE(15);
      if (lookahead != 0) ADVANCE(13);
      END_STATE();
    case 3:
      if (lookahead == '-') ADVANCE(1);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(2);
      if (lookahead != 0) ADVANCE(13);
      END_STATE();
    case 5:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(11);
      if (lookahead != 0 &&
          lookahead != 0xbb) ADVANCE(12);
      END_STATE();
    case 6:
      if (eof) ADVANCE(8);
      if (lookahead == '\n') SKIP(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(17);
      if (lookahead != 0) ADVANCE(16);
      END_STATE();
    case 7:
      if (eof) ADVANCE(8);
      if (lookahead == '-') ADVANCE(4);
      if (lookahead == 0xab) ADVANCE(9);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(14);
      if (lookahead != 0) ADVANCE(13);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_u00ab);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_u00bb);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_entry_id);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(11);
      if (lookahead != 0 &&
          lookahead != 0xbb) ADVANCE(12);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_entry_id);
      if (lookahead != 0 &&
          lookahead != 0xbb) ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(aux_sym__inner_token1);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(aux_sym__inner_token1);
      if (lookahead == '-') ADVANCE(4);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(14);
      if (lookahead != 0 &&
          lookahead != 0xab) ADVANCE(13);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_note_prefix);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym_note_content_token1);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_note_content_token1);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(17);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(16);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 7},
  [5] = {.lex_state = 7},
  [6] = {.lex_state = 6},
  [7] = {.lex_state = 7},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 6},
  [10] = {.lex_state = 6},
  [11] = {.lex_state = 5},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 7},
  [16] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_u00ab] = ACTIONS(1),
    [anon_sym_u00bb] = ACTIONS(1),
    [sym_note_prefix] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(12),
    [sym_entry] = STATE(2),
    [sym_entry_marker] = STATE(7),
    [aux_sym_source_file_repeat1] = STATE(2),
    [anon_sym_u00ab] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(3), 1,
      anon_sym_u00ab,
    ACTIONS(5), 1,
      ts_builtin_sym_end,
    ACTIONS(7), 1,
      sym_note_prefix,
    STATE(7), 1,
      sym_entry_marker,
    STATE(14), 1,
      sym_note,
    STATE(3), 2,
      sym_entry,
      aux_sym_source_file_repeat1,
  [20] = 4,
    ACTIONS(11), 1,
      anon_sym_u00ab,
    STATE(7), 1,
      sym_entry_marker,
    ACTIONS(9), 2,
      ts_builtin_sym_end,
      sym_note_prefix,
    STATE(3), 2,
      sym_entry,
      aux_sym_source_file_repeat1,
  [35] = 4,
    ACTIONS(14), 1,
      ts_builtin_sym_end,
    ACTIONS(18), 1,
      aux_sym__inner_token1,
    STATE(5), 1,
      aux_sym__inner,
    ACTIONS(16), 2,
      anon_sym_u00ab,
      sym_note_prefix,
  [49] = 4,
    ACTIONS(20), 1,
      ts_builtin_sym_end,
    ACTIONS(24), 1,
      aux_sym__inner_token1,
    STATE(5), 1,
      aux_sym__inner,
    ACTIONS(22), 2,
      anon_sym_u00ab,
      sym_note_prefix,
  [63] = 4,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
    ACTIONS(29), 1,
      aux_sym_note_content_token1,
    STATE(9), 1,
      aux_sym_note_content_repeat1,
    STATE(16), 1,
      sym_note_content,
  [76] = 3,
    ACTIONS(31), 1,
      aux_sym__inner_token1,
    STATE(4), 1,
      aux_sym__inner,
    STATE(8), 1,
      sym_entry_content,
  [86] = 1,
    ACTIONS(33), 3,
      ts_builtin_sym_end,
      anon_sym_u00ab,
      sym_note_prefix,
  [92] = 3,
    ACTIONS(35), 1,
      ts_builtin_sym_end,
    ACTIONS(37), 1,
      aux_sym_note_content_token1,
    STATE(10), 1,
      aux_sym_note_content_repeat1,
  [102] = 3,
    ACTIONS(39), 1,
      ts_builtin_sym_end,
    ACTIONS(41), 1,
      aux_sym_note_content_token1,
    STATE(10), 1,
      aux_sym_note_content_repeat1,
  [112] = 1,
    ACTIONS(44), 1,
      sym_entry_id,
  [116] = 1,
    ACTIONS(46), 1,
      ts_builtin_sym_end,
  [120] = 1,
    ACTIONS(48), 1,
      anon_sym_u00bb,
  [124] = 1,
    ACTIONS(50), 1,
      ts_builtin_sym_end,
  [128] = 1,
    ACTIONS(52), 1,
      aux_sym__inner_token1,
  [132] = 1,
    ACTIONS(54), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 20,
  [SMALL_STATE(4)] = 35,
  [SMALL_STATE(5)] = 49,
  [SMALL_STATE(6)] = 63,
  [SMALL_STATE(7)] = 76,
  [SMALL_STATE(8)] = 86,
  [SMALL_STATE(9)] = 92,
  [SMALL_STATE(10)] = 102,
  [SMALL_STATE(11)] = 112,
  [SMALL_STATE(12)] = 116,
  [SMALL_STATE(13)] = 120,
  [SMALL_STATE(14)] = 124,
  [SMALL_STATE(15)] = 128,
  [SMALL_STATE(16)] = 132,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [11] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [14] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entry_content, 1, 0, 0),
  [16] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_entry_content, 1, 0, 0),
  [18] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [20] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__inner, 2, 0, 0),
  [22] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__inner, 2, 0, 0),
  [24] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__inner, 2, 0, 0), SHIFT_REPEAT(5),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_note, 1, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entry, 2, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_note_content, 1, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_note_content_repeat1, 2, 0, 0),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_note_content_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [46] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entry_marker, 3, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_note, 2, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_ats(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "ats",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
